name = "worker-backend"
main = "worker-backend.js"
compatibility_date = "2024-07-01"

[[kv_namespaces]]
binding = "SETTINGS"
id = "<your_kv_id>"

[[kv_namespaces]]
binding = "APP_KV"
id = "<your_app_kv_id>"

[[ai]]
binding = "AI"
